---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: vagrant-ubuntu-12.04
    box_url: http://files.vagrantup.com/precise64.box
    require_chef_omnibus: true
  run_list:
  - recipe[apt]
# TODO: Centos/RHEL Support
#- name: centos-6.4
#  driver_config:
#    box: opscode-centos-6.4
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
#- name: centos-5.9
#  driver_config:
#    box: opscode-centos-5.9
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[postfix]
  - recipe[mysql::server]
  - recipe[ghost::database]
  - recipe[ghost::default]
  - recipe[ghost::nginx]
  attributes: 
    ghost:
      src_url: "http://9e87a4a4938b37400365-4b32c69b6a5b0272c45e310ebc459666.r98.cf2.rackcdn.com/Ghost-0.3.3.zip"
      db_admin_password: "foobar"
      db_password: "ghost"
      themes:
        ghostwriter: "https://github.com/roryg/ghostwriter.git"
        swayze: "http://ghost-themes.s3.amazonaws.com/swayze/swayze.zip"
    mysql:
      bind_address: "127.0.0.1"
      server_root_password: "foobar"
      server_repl_password: "foobar"
      server_debian_password: "foobar"
    authorization:
      sudo:
        users: [ "vagrant", "ghost" ]
